r=float(input('shoae dayere ra vared konid :'))
h=float(input('ertefae ostovane ra vared konid : '))
mohitedayere=2*3.14*r
masahatedayere=3.14*r*r
masahatejanebi=mohitedayere*h
hajm=masahatedayere*h
masahatekol=2*masahatedayere+masahatejanebi
print('masahate janebi =', masahatejanebi)
print('masahate kol =', masahatekol)
print('hajm = ', hajm)